### ISSUE TITLE
Some Minecraft Accounts don't work

### ISSUE THREAD

**Issue by CranosTV** [MauritsWilke/mcpfp#21]
Mine for example: Cran0s

**Comment by MauritsWilke** [comment]
The username does give a profile picture for me, could you use `ctrl+shift+i` to check the console for any errors?

**Comment by MauritsWilke** [comment]
I think the issue has to do with rate limiting on minotar's end because of Mojang rate limiting requests by usernames (as opposed to UUID's). 
The issue is that if I request the UUID myself, it will get rate limited again. That is what happened when the site blew up and why I implemented minotar. I'll look into the issue again, though.

**Comment by Meeweegaming** [comment]
Mine's goes to steve when i enter my username: meweegaming

**Comment by Meeweegaming** [comment]
UUID:
04c8404c-2ada-424b-85a6-99d42e60cad2
04c8404c2ada424b85a699d42e60cad2

Can you get it to work?

**Comment by MauritsWilke** [comment]
Works now
