### ISSUE TITLE
Would you like to create an API based on MinecraftPFP?

### ISSUE THREAD

**Issue by ValentinStars** [MauritsWilke/mcpfp#46]
I would like to use your generator in various bots and personal projects.

**Comment by Eldarabdullayew** [comment]
Ghh

**Comment by Eldarabdullayew** [comment]
Hbh

**Comment by Eldarabdullayew** [comment]
Ghh

**Comment by Eldarabdullayew** [comment]
Ghh

**Comment by UdoyBH** [comment]
> I would like to use your generator in various bots and personal projects.

someone tried to make an api based on this
https://github.com/towsifkafi/mcpfp

**Comment by MauritsWilke** [comment]
There already is an API, has been since the beginning:
`https://minecraftpfp.com/api/pfp/{USERNAME}.png?gradient={HEX}-{HEX}`
The username can just be replaced and the gradient is optional, it can take as many (or zero) hex codes:

`https://minecraftpfp.com/api/pfp/I_Like_Cats__.png?gradient=fdeff9-ec38bc-7303c0-03001e`
