### ISSUE TITLE
Imagine stealing from bitzel and giving no credits

### ISSUE THREAD

**Issue by Astrolightee** [MauritsWilke/mcpfp#6]

**Comment by MauritsWilke** [comment]
I assume you are referring to the following video: [https://www.youtube.com/watch?v=2_VWUkZH06g](https://www.youtube.com/watch?v=2_VWUkZH06g)

My generated profile pictures and Bitzel’s art have only the theme "Pixel Art" in common. The true inspiration for this project came from when I used to do Fiverr and saw the amount of “Minecraft Pixel Art Profile Pictures” which were all incredibly similar to my now-generated PFPs. Because I am a programmer, I thought of a way to automate it.

I figured out the stitching of the skin myself and can prove so with older versions of the project along with a lot of testing screenshots from an old discord chat. If you really feel the need to prove your point, I can link said files.

My work is my own and is only inspired by works of *multiple* people and not one individual. One person does not own an art style, and seemingly Bitzel didn't create it either (and neither am I claiming to be the original creator.) My program simply automates the creation of a style of profile pictures.

Hopefully you understand me.

## Evidence
My Fiverr page: https://www.fiverr.com/maurits_wilke/make-you-a-minecraft-pixel-art-profile-picture
Example of referenced Fiverr stores:
<img width=400 height=auto src="https://user-images.githubusercontent.com/34707512/187047571-69a5484c-663a-4269-b386-f0280f8a0569.png"/>

**Comment by MauritsWilke** [comment]
Been a week without reply, closing issue

**Comment by AndrewDTR** [comment]
@MauritsWilke not going to go into what I fully think here, as I doubt I'm going to be able to change what you think regarding the originality of these profile pictures, but your point about people being "unable to own art styles" is completely invalid and inconsistent with how artists work. art existing through

**Comment by AndrewDTR** [comment]
@MauritsWilke not going to go into what I fully think here, as I doubt I'm going to be able to change what you think regarding the originality of these profile pictures, but your point about people being "unable to own art styles" is completely invalid and inconsistent with how artists work. pixel art existing doesn't make it inherently more 'simple' or easier to draw, and i feel like there is some intentional negligence by refusing to acknowledge the origin of the art you're creating programmatically. i find it interesting how you linked to a video and fiverr pages made _well_ after the popularity of this specific iteration of profile picture, but haven't acknowledged the [original design done by bitzel](https://twitter.com/BitzelYT/status/1246631811628834818), nor [the video that he made in detail](https://youtu.be/_Vd3d-9al74) to explain how to draw it by hand. the strange irony is that the picture you chose from fiverr uses a creator [whose profile image is blatantly inspired by bitzel's own skin](https://img.draw.rest/u/4FpTnb.png). am i saying that automating such a process is unethical? no, not necessarily. but i think making something that is undeniably inspired by a creator's art style (as i've discussed above) and then deciding to monetize it through adsense without giving any passing reference to its inspiration ( https://github.com/MauritsWilke/mcpfp/commit/e016b7299b03ffb95090c9e4fed1db803d817952 ) is incredibly dodgy. especially when mitigation is -- in its simplest form -- just giving basic credit and acknowledgement to a single person. i just find it genuinely difficult to imagine that you're unaware of this style's origins. i can only hope that this brings light to it and inspires you to give proper credit where it's due. thanks!

**Comment by MauritsWilke** [comment]
I have already responded to this, closing issue.
